POST http://localhost:3000/api/v1/church
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zMmQ1MUo5TW1RbG43d1lsUzUzQ1dRWE1IZk4iLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NjEyNjY3MzIsImZ2YSI6WzU3NzQsLTFdLCJpYXQiOjE3NjEyNjY2NzIsImlzcyI6Imh0dHBzOi8vbm9ibGUtY2hpcG11bmstODguY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzYxMjY2NjYyLCJzaWQiOiJzZXNzXzM0SjhJbUY3RXpKMEJlN2F0TjUzbEdFaEx1ayIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzRKOElqUk9wNnh3OGZkTk9BN3lFWXVZcWl3IiwidiI6Mn0.rtqWgPPVVv2wI3cloYfDi2GRrXOzCiBl0ohlDDfnFWZGJxAOng57nKiwIyjX5ARA9LcttQVgq7nbEsQXLqbFbhT9wJHxyfEpENxh8o-ZneoSGYY1byd_amvn_bJKRdv3YCATgYqqF3rqAOhLiAdfGX6rRTrslWPI2Rhln7qWRNwknIkMOqTGBjYqGaaQ90l9g526jwKcRFzsknZenhBIGdyZ0t77HVBvh4YcfvvZwGfU6nVc7e_LlFE8FXvSnZQrZkBHqPsqES7pwhcUfVcg3wWcVrE_oYyDaQ-fA4dtFztZpgM0whumj5jkfypvV4Y0PM5VYpifcpFhcb3nVntCAQ

{
    "businessName": "Igreja",
    "publicName": "Igreja",
    "cnpj": "85760094000150",   
    "contactInfo":[
        {
            "type": "phone",
            "value": "11952066489"
        },
         {
            "type": "phone",
            "value": "11952066489"
        },
         {
            "type": "phone",
            "value": "11952066489"
        }
    ],
    "pastor": "currentUser",
    "address": {
        "street": "Rua José Teixeira de Oliveira",
        "number": "81",
        "neighborhood": "Água espraiada",
        "state": "SP",
        "city": "Cotia",
        "zipCode": "06726486"
    },
    "plan": "starter"
}

###
GET http://localhost:3000/api/v1/church
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18zMmQ1MUo5TW1RbG43d1lsUzUzQ1dRWE1IZk4iLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NjEyNjc5OTIsImZ2YSI6WzU3OTUsLTFdLCJpYXQiOjE3NjEyNjc5MzIsImlzcyI6Imh0dHBzOi8vbm9ibGUtY2hpcG11bmstODguY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzYxMjY3OTIyLCJzaWQiOiJzZXNzXzM0SjhJbUY3RXpKMEJlN2F0TjUzbEdFaEx1ayIsInN0cyI6ImFjdGl2ZSIsInN1YiI6InVzZXJfMzRKOElqUk9wNnh3OGZkTk9BN3lFWXVZcWl3IiwidiI6Mn0.IwDuS8svyLKpKSoCViAa3tHhb25dQPo4AVD8xQLQ2BnxryevEy2Yr82B8Kgulglt2n3M9C3GMgbdHiiVM0rzNaDBSHJMdLMatnq_HvBKNTX4n-USty__v6gAru_mlN0-iBkFujFzFzav2SGRkqI29axqxOIRqR8HQ_TS4ElqhO8lWv279zTNYLhtomV8fhNpUrTKaNRjzKo2GgDvKMxAykEW3DFwelzKwCN1Hbr1MshvoDfYWnGJDz_lxd5XqN678lfmoJnXwF_NLJKMIyMmb5KjkFtgpr18Y4zv2il2SRBi2grthpjvC_QFIS54znljJyE8O7WfvlUWG66vqlRPAw